### ISSUE TITLE
Show error message if FILEPILE_KEY not entered

### ISSUE THREAD

**Issue by kilrizzy** [filepileio/filepile-laravel#1]
Currently shows as:

 [GuzzleHttp\Exception\ClientException]
  Client error: `GET http://filepile.app/api/v1/account/pile` resulted in a `401 Unauthorized` response:
  {"message":"Unauthenticated."}

Should instead display as a command error message stating "You haven't configured your FilePile API key"

**Comment by rafa-acioly** [comment]
#7 should fix this as well.

but instead of saying  "You haven't configured your FilePile API key" you could just keep "Ops, look like your key is invalid", what you think?
