### ISSUE TITLE
[ErrorException]   mkdir(): No such file or directory

### ISSUE THREAD

**Issue by GabMic** [filepileio/filepile-laravel#12]
Been trying filepile today, but yet found a way to properly use it. 
I follow all the guides and videos, but still, i get this issue. 
`  [ErrorException]
  mkdir(): No such file or directory
`

**Comment by kilrizzy** [comment]
Thanks for the info! 

I think this may have been due to a forward-slash prefix issue when trying to install to the root project directory.  I made a few updates if you don't mind giving the latest 1.1.7 version a shot and let me know if that's working for you
