### ISSUE TITLE
Show error message if FILEPILE_KEY is invalid

### ISSUE THREAD

**Issue by kilrizzy** [filepileio/filepile-laravel#2]
Currently shows as:

[GuzzleHttp\Exception\ClientException]
Client error: GET http://filepile.app/api/v1/account/pile resulted in a 401 Unauthorized response:
{"message":"Unauthenticated."}

Should instead display as a command error message stating "Unable to authenticate, please verify your FilePile API key"

**Comment by rafa-acioly** [comment]
Hey @kilrizzy can you give more details about it? where should i start looking?

**Comment by kilrizzy** [comment]
Currently we have /src/API/Client.php which is just a wrapper for Guzzle.  In both /src/Commands/FilePileList and FilePileInstallPile this $apiClient is called and then the response is decoded. 

Instead, it seems we'll want to try and catch any of these errors first and display a nicer message accordingly using artisan's $this->error(...);

**Comment by rafa-acioly** [comment]
can you explain how can i run as "dev mod"?

**Comment by kilrizzy** [comment]
I've been symlinking into a fresh laravel application and working from there. Still need unit testing to be integrated to make the process smoother.

When installed into a laravel app, for this issue adding any vlaue as FILEPILE_KEY in your .env would work for testing against failure. Or a real one would be obtained with a filepile.io account. Alternatively the FILEPILE_BASE_URI var could be set with a mock api to use instead of the live, but this would obviously be much more complex to setup.

**Comment by rafa-acioly** [comment]
what i mean is, how i can download the package and run manually? if i download using `composer` this is will not contain any `.git` tracking.

**Comment by kilrizzy** [comment]
Symlinking in composer should fix this so you can work locally and composer will use your local package, hopefully this answers your question:
- I have a fresh laravel app at /Code/file-pile-demo
- I have my development package at /Code/packages/filepile/filepile-laravel

in my file-pile-demo project, this is my composer.json, note the repositories field pointing to my local path so that is what is pulled for the package. 

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories": [
        {
            "type": "path",
            "url": "../packages/filepile/filepile-laravel",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        "php": ">=7.0.0",
        "fideloper/proxy": "~3.3",
        "filepileio/filepile-laravel": "dev-master",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
```

**Comment by rafa-acioly** [comment]
#7 
hope it helps, if you don't like let me know to fix it!

**Comment by kilrizzy** [comment]
Thanks! This looks closer but any thoughts on how we might push that error back to the command that calls the client? That way we can display the error in the same $this->error() method

I wonder if catching the error from the command would be a better way to go? So for example in /src/Commands/FilePileList.php Line 41:

try {
	$response = $apiClient->call('GET','/api/v1/account/pile');
} catch (\GuzzleHttp\Exception\ClientException $error){
	$this->error('oops...');
}

Perhaps the better solution is to create our own exceptions for the Client wrapper so we don't rely on Guzzle specific ones? So Client would throw an APIKeyInvalidException and we would catch that on the commands and alert accordingly. Just a thought

I should have some time tonight to give it a whirl if you don't get a chance to. Thanks for your help with this!

**Comment by rafa-acioly** [comment]
agree with you, this will be the best scenario! but you can open a new issue to implement this and merge this solutions for a while, unfortunately my day is full and i can't do what you suggest, I'm sorry.

**Comment by kilrizzy** [comment]
No worries, tonight I'll pull this in and roll with it
