### ISSUE TITLE
No permission to write or create directories

### ISSUE THREAD

**Issue by rafa-acioly** [filepileio/filepile-laravel#9]
i've tested the `package` and notice that the `is_writeable` start apply since `/home` directory, in fact this directory is not writable, the validation should start after `base_path()`; we can see the validation starting [from here](https://github.com/filepileio/filepile-laravel/blob/master/src/Support/Files/FileWriter.php#L26)

**Comment by kilrizzy** [comment]
Ah, you're right looks like I merged that a bit too quick. 

Really, there's no need to do that check if the file / directory already exists anyway. I'll patch that now

**Comment by kilrizzy** [comment]
I was still having trouble with is_writable even after being in base_path() so I just killed the check for now. Good find

**Comment by rafa-acioly** [comment]
i've finished a refactor for the `FileWriter` classe that apply the "S" from `solid`.

- What was done?
The function that was creating the directories was the same that create the file, now they are separated each one with your task.

- How it was done?
2 new functions are available `createFile` and `createDirectories` each one do exactly was the function name describe.

With 2 distinct functions now we can [check if the directories and the file was created before including content into the file](https://github.com/rafa-acioly/filepile-laravel/blob/filewriter_restruct/src/Commands/FilePileInstallPile.php#L137).

If you like i can make a new pull request! you can [see the changes](https://github.com/rafa-acioly/filepile-laravel/blob/filewriter_restruct/src/Support/Files/FileWriter.php) on file.

**Comment by kilrizzy** [comment]
Awesome just tested and worked great for me. Toss up a PR and I'll bring it in
